### PR TITLE
importlib_metadata 3.6 and Python 3.12 compat fix

### PR DESCRIPTION
**Pull request by cpu**
:wave: After setting up `ldmud-efuns` in a fresh venv w/ Python 3.12+ I noticed the following error at startup and no efuns/types being registered:

```
Traceback (most recent call last):
  File "/home/daniel/Code/C/ldmud/python/startup.py", line 3, in <module>
    startup()
  File "/home/daniel/Code/C/ldmud/.venv/lib/python3.12/site-packages/ldmudefuns/startup.py", line 33, in startup
    for entry_point in eps.get(ep_name,()):
                       ^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

The root cause is a breaking change described [in the `importlib.metadata` docs](https://docs.python.org/3/library/importlib.metadata.html#functional-api):

> Changed in version 3.12: The “selectable” entry points were introduced in importlib_metadata 3.6 and Python 3.10. Prior to those changes, entry_points accepted no parameters and always returned a dictionary of entry points, keyed by group. With importlib_metadata 5.0 and Python 3.12, entry_points always returns an EntryPoints object. 

This branch works around that change so the package continues to work with Python 3.12+ and importlib_metadata 5.0+.

I couldn't help but tidy up some duplication commit-by-commit before implementing the fix. If you'd prefer a more minimal diff I'd be happy to rework the branch.

### CODE REVIEW

**Comment by cpu** [comment]
Reworked to use `internal.py` instead of `__init__.py`, and to avoid `_` prefixing the helper names based on OOB feedback.
